# Generated by Django 2.2.2 on 2019-06-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('contact_number', models.CharField(help_text='В формате +7(999)1234-567', max_length=15, verbose_name='Контактный телефон')),
                ('specialties', models.ManyToManyField(related_name='clinics', to='clinics.Specialty')),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
            },
        ),
    ]
