# Generated by Django 2.2.2 on 2019-06-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_auto_20190622_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='specialties',
            field=models.ManyToManyField(related_name='clinics', to='clinics.Specialty', verbose_name='Доступные специальности'),
        ),
    ]
