# Generated by Django 2.2.2 on 2019-06-23 05:35

import clinics.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_auto_20190622_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='ФИО')),
                ('passport_number', models.CharField(help_text='10 цифр без пробелов', max_length=10, verbose_name='Серия и номер паспорта')),
                ('contact_number', clinics.model_fields.ContactPhoneField(help_text='В формате +7(999)123-45-67', max_length=16, verbose_name='Контактный телефон')),
            ],
        ),
        migrations.AlterField(
            model_name='clinic',
            name='contact_number',
            field=clinics.model_fields.ContactPhoneField(help_text='В формате +7(999)123-45-67', max_length=16, verbose_name='Контактный телефон'),
        ),
    ]
