# Generated by Django 2.2.2 on 2019-06-23 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_auto_20190623_0535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
    ]
