# Generated by Django 2.2.2 on 2019-06-23 06:21

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0005_auto_20190623_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Создана'), ('IN_PROGRESS', 'Обрабатывается'), ('PROCESSED', 'Обработана'), ('PATIENT_REFUSED', 'Пациент отказался')], default=orders.models.OrderStatus('Создана'), max_length=255, verbose_name='Статус')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clinics.Clinic', verbose_name='Требуемая клиника')),
                ('patient', models.ForeignKey(help_text='Пациент, оставивший заявку', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clinics.Patient', verbose_name='Заявитель')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clinics.Specialty', verbose_name='Требуемый специалист')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
