# Generated by Django 2.2.2 on 2019-06-23 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTimeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='Начало')),
                ('ends_at', models.DateTimeField(verbose_name='Конец')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_time_ranges', to='orders.Order')),
            ],
            options={
                'verbose_name': 'Удобное для пациента время',
                'verbose_name_plural': 'Удобные для пациента временные промежутки',
            },
        ),
        migrations.CreateModel(
            name='ClinicTimeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='Начало')),
                ('ends_at', models.DateTimeField(verbose_name='Конец')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_time_ranges', to='orders.Order')),
            ],
            options={
                'verbose_name': 'Удобное для клиники время',
                'verbose_name_plural': 'Удобные для клиники временные промежутки',
            },
        ),
    ]
