# Generated by Django 2.2.2 on 2019-06-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190623_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='appointment_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время приёма'),
        ),
    ]
